export { default as IndividualHeader } from "./individual-header"
export { default as BusinessHeader } from "./business-header"
export { default as PaymentTool } from "./payment-tool"
export { default as PayBills } from "./paybills"
export { default as SendFunds } from "./sendFunds"